name: Test OIDC Authentication

on:
  workflow_dispatch:   # ✅ Manually trigger this workflow from GitHub Actions 

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # ✅ Required for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::546821226186:role/github-action-oidc
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity
