name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::546821226186:role/github-action-oidc
          aws-region: ap-south-1

      - name: Deploy static files to S3
        run: |
          aws s3 rm s3://d-f-dev.wagholi.co/ --recursive
          aws s3 cp . s3://d-f-dev.wagholi.co/ --recursive --exclude ".git/*" --exclude ".github/*"
          
      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id XXXX111 \
            --paths '/*'
